### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by parul12111** [zhanght021/RPT#12]
(rpt) C:\Users\jinda\OneDrive\Desktop\RPT-master>python eval.py    --tracker_path ./results    --dataset VOT2018   --tracker_prefix siamreppoints       --num 1
loading VOT2018: 100%|██████████████████████████████████| 60/60 [00:00<00:00, 80.93it/s, zebrafish1]
eval ar: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.52it/s]
eval eao:   0%|                                                               | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\jinda\anaconda3\envs\rpt\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\jinda\OneDrive\Desktop\RPT-master\toolkit\evaluation\eao_benchmark.py", line 47, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File "C:\Users\jinda\OneDrive\Desktop\RPT-master\toolkit\evaluation\eao_benchmark.py", line 110, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval.py", line 152, in <module>
    main()
  File "eval.py", line 134, in main
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "C:\Users\jinda\anaconda3\envs\rpt\lib\site-packages\tqdm\std.py", line 1176, in __iter__
    for obj in iterable:
  File "C:\Users\jinda\anaconda3\envs\rpt\lib\multiprocessing\pool.py", line 735, in next
    raise value
ValueError: max() arg is an empty sequence

please help me to resolve this error
guide me where i am wrong

**Comment by zhanght021** [comment]
Maybe you should change --tracker_prefix siamreppoints to --tracker_prefix 'siamreppoints'
@parul12111

**Comment by parul12111** [comment]
Thank you for your immediate response
but when i execute the code i got this error
(rpt) C:\Users\jinda\OneDrive\Desktop\RPT-master>python eval.py --tracker_path ./results --dataset VOT2018 --tracker_prefix 'siamreppoints'
Traceback (most recent call last):
  File "eval.py", line 152, in <module>
    main()
  File "eval.py", line 44, in main
    assert len(trackers) > 0
AssertionError

**Comment by zhanght021** [comment]
hello,  this error is caused by it can not find your results file folder.   the results folder'name must be same with the word followed by --tracker_prefix. @parul12111 

we used the raw pysot structure from https://github.com/STVIR/pysot, we only intergate our algorithminto the pysot structure.

**Comment by parul12111** [comment]
ok thank you for your valuable feedback

**Comment by estrelasy** [comment]
I have the same problem with you. Have you solved it? And I want to know how you solved it. @parul12111
